package com.bretthalliday.fdtuner.model

/**
 * GENERATED from jackhumbert fardriver.hpp — DO NOT hand-edit addresses (re-run the generator).
 * Word address / byte / bit positions are computed from the struct layout and validated.
 * Scales: curated where known + best-effort from comments; verify unitless ones.
 * Requires a SECTION_DIAGNOSTICS = "Diagnostics" constant (read-only state/telemetry).
 */
object GeneratedParamDefs {
    val all: List<ParamDef> = listOf(
        ParamDef(name = "VolCoeff", addr = 0x00, section = "FixedParas"),
        ParamDef(name = "Voltage2Coeff", addr = 0x01, section = "FixedParas"),
        ParamDef(name = "PhaseACoeff", addr = 0x02, section = "FixedParas"),
        ParamDef(name = "LineCoeff", addr = 0x03, section = "FixedParas"),
        ParamDef(name = "PhaseCCoeff", addr = 0x04, section = "FixedParas"),
        ParamDef(name = "SaveNum", addr = 0x05, section = "FixedParas"),
        ParamDef(name = "Arg2", addr = 0x06, section = "Functions", isLoByte = true, bitMask = 0x01),
        ParamDef(name = "Protocol485", addr = 0x06, section = "Functions", isLoByte = true, bitMask = 0x0F, bitShift = 2),
        ParamDef(name = "MorseCode", addr = 0x06, section = "Functions", isHiByte = true, bitMask = 0x7F),
        ParamDef(name = "SpeedKI", addr = 0x07, section = "PID Paras", isLoByte = true),
        ParamDef(name = "SppedKP", addr = 0x07, section = "PID Paras", isHiByte = true),
        ParamDef(name = "ThrottleLow", addr = 0x08, section = "Functions", scale = 20.0f, unit = "V", isLoByte = true),
        ParamDef(name = "ThrottleHigh", addr = 0x08, section = "Functions", scale = 20.0f, unit = "V", isHiByte = true),
        ParamDef(name = "FAIF", addr = 0x09, section = "Functions"),
        ParamDef(name = "CurveTime", addr = 0x0A, section = "Functions"),
        ParamDef(name = "PhaseExchange", addr = 0x0B, section = "Functions", isLoByte = true, bitMask = 0x01),
        ParamDef(name = "SlowDown", addr = 0x0B, section = "Functions", isHiByte = true, bitMask = 0x07),
        ParamDef(name = "PC13Config", addr = 0x0B, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "CurrAntiTheft", addr = 0x0B, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "Direction", addr = 0x0B, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "PhaseOffset", addr = 0x0C, section = "PID Paras", scale = 10.0f, unit = "V"),
        ParamDef(name = "ZeroBattCoeff", addr = 0x0D, section = "PID Paras"),
        ParamDef(name = "FullBattCoeff", addr = 0x0E, section = "PID Paras"),
        ParamDef(name = "StartKI", addr = 0x0F, section = "PID Paras", isLoByte = true),
        ParamDef(name = "MidKI", addr = 0x0F, section = "PID Paras", isHiByte = true),
        ParamDef(name = "MaxKI", addr = 0x10, section = "PID Paras", isLoByte = true),
        ParamDef(name = "StartKP", addr = 0x10, section = "PID Paras", isHiByte = true),
        ParamDef(name = "MidKP", addr = 0x11, section = "PID Paras", isLoByte = true),
        ParamDef(name = "MaxKP", addr = 0x11, section = "PID Paras", isHiByte = true),
        ParamDef(name = "LD", addr = 0x12, section = "Parameters"),
        ParamDef(name = "AlarmDelay", addr = 0x13, section = "Parameters"),
        ParamDef(name = "PolePairs", addr = 0x14, section = "Parameters", isLoByte = true, isSafetyCritical = true),
        ParamDef(name = "MaxSpeed", addr = 0x15, section = "Parameters", scale = 4.0f, unit = "A", isSafetyCritical = true),
        ParamDef(name = "RatedPower", addr = 0x16, section = "Parameters"),
        ParamDef(name = "RatedVoltage", addr = 0x17, section = "Parameters", scale = 10.0f, unit = "V", isSafetyCritical = true),
        ParamDef(name = "RatedSpeed", addr = 0x18, section = "Parameters", scale = 4.0f, unit = "A"),
        ParamDef(name = "MaxLineCurr", addr = 0x19, section = "Parameters", scale = 4.0f, unit = "A", isSafetyCritical = true),
        ParamDef(name = "WeakA", addr = 0x1A, section = "Parameters", isLoByte = true, bitMask = 0x03),
        ParamDef(name = "SpeedPulse", addr = 0x1A, section = "Parameters", isLoByte = true, bitMask = 0x1F, bitShift = 2),
        ParamDef(name = "LQ", addr = 0x1B, section = "Parameters"),
        ParamDef(name = "BattRatedCap", addr = 0x1C, section = "Parameters"),
        ParamDef(name = "IntRes", addr = 0x1D, section = "Parameters"),
        ParamDef(name = "FwReRatio", addr = 0x1E, section = "Functions", isLoByte = true),
        ParamDef(name = "ReverseSideStandSignal", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01),
        ParamDef(name = "AllowSmallCurrentSwitching", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "NeutralAntiSkidParking", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "RecordMileage", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "LowerMagneticBrake", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "DownhillReverseOvervoltageCutoff", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "ShieldedGearSpeedLimit2", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "PD1Input", addr = 0x1E, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "LowVolProtect", addr = 0x1F, section = "Protect", scale = 10.0f, unit = "V", isSafetyCritical = true),
        ParamDef(name = "BCState", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01),
        ParamDef(name = "SeatEnable", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "PEnable", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "AutoBackPEnable", addr = 0x21, section = "Energy Regenerate", isLoByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "CruiseEnable", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "EABSEnable", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "PushEnable", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "ForceAntiTheft", addr = 0x21, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "OverSpeedAlarm", addr = 0x21, section = "Functions", isHiByte = true, bitMask = 0x01),
        ParamDef(name = "BrakeStillPark", addr = 0x21, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "RememberGear", addr = 0x21, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "BackEnable", addr = 0x21, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "RelayDelay1S", addr = 0x21, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "ModelYear", addr = 0x22, section = "Product", isLoByte = true),
        ParamDef(name = "ModelMonth", addr = 0x22, section = "Product", isHiByte = true),
        ParamDef(name = "ModelDay", addr = 0x23, section = "Product", isLoByte = true),
        ParamDef(name = "TimeHour", addr = 0x23, section = "Functions", isHiByte = true),
        ParamDef(name = "TimeMin", addr = 0x24, section = "Parameters", isLoByte = true),
        ParamDef(name = "TimeSecond", addr = 0x24, section = "Parameters", isHiByte = true),
        ParamDef(name = "HighVolProtect", addr = 0x25, section = "Protect", scale = 10.0f, unit = "V", isSafetyCritical = true),
        ParamDef(name = "CustomMaxLineCurr", addr = 0x26, section = "Parameters", scale = 4.0f, unit = "A", isSafetyCritical = true),
        ParamDef(name = "CustomMaxPhaseCurr", addr = 0x27, section = "Parameters", scale = 4.0f, unit = "A", isSafetyCritical = true),
        ParamDef(name = "BackSpeed", addr = 0x28, section = "Parameters", scale = 4.0f, unit = "A"),
        ParamDef(name = "LowSpeed", addr = 0x29, section = "Parameters", scale = 4.0f, unit = "A"),
        ParamDef(name = "MidSpeed", addr = 0x2A, section = "Parameters", scale = 4.0f, unit = "A"),
        ParamDef(name = "Max_Dec", addr = 0x2B, section = "Parameters"),
        ParamDef(name = "FreeThrottle", addr = 0x2C, section = "Parameters", isLoByte = true),
        ParamDef(name = "MaxPhaseCurr", addr = 0x2D, section = "Parameters", scale = 4.0f, unit = "A", isSafetyCritical = true),
        ParamDef(name = "SpeedAnalog", addr = 0x2E, section = "Parameters"),
        ParamDef(name = "Max_Acc", addr = 0x2F, section = "Parameters"),
        ParamDef(name = "StopBackCurr", addr = 0x30, section = "Energy Regenerate", scale = 4.0f, unit = "A"),
        ParamDef(name = "MaxBackCurr", addr = 0x31, section = "Energy Regenerate", scale = 4.0f, unit = "A"),
        ParamDef(name = "LowSpeedLineCurr", addr = 0x32, section = "Parameters", isLoByte = true),
        ParamDef(name = "MidSpeedLineCurr", addr = 0x32, section = "Parameters", isHiByte = true),
        ParamDef(name = "LowSpeedPhaseCurr", addr = 0x33, section = "Parameters", isLoByte = true),
        ParamDef(name = "MidSppedPhaseCurr", addr = 0x33, section = "Parameters", isHiByte = true),
        ParamDef(name = "BlockTime", addr = 0x34, section = "Parameters"),
        ParamDef(name = "SpdPulseNum", addr = 0x35, section = "Parameters"),
        ParamDef(name = "MaxLineCurr2", addr = 0x63, section = "FixedParas"),
        ParamDef(name = "MaxPhaseCurr2", addr = 0x64, section = "FixedParas"),
        ParamDef(name = "MotorDia", addr = 0x65, section = "FixedParas", isLoByte = true),
        ParamDef(name = "TempCoeff", addr = 0x66, section = "FixedParas"),
        ParamDef(name = "ProdMaxVol", addr = 0x67, section = "FixedParas", scale = 10.0f, unit = "V"),
        ParamDef(name = "ISMax", addr = 0x68, section = "FixedParas"),
        ParamDef(name = "LmtSpeed", addr = 0x69, section = "Display"),
        ParamDef(name = "DistanceLSB", addr = 0x6A, section = "Display", scale = 10.0f, unit = "V"),
        ParamDef(name = "ParaIndex", addr = 0x6B, section = "Display", isLoByte = true),
        ParamDef(name = "SpecialCode", addr = 0x6B, section = "Display", isHiByte = true),
        ParamDef(name = "WeakTime", addr = 0x7C, section = "Display", isLoByte = true, bitMask = 0x07, bitShift = 1),
        ParamDef(name = "QuickDown", addr = 0x7C, section = "Display", isLoByte = true, bitMask = 0x07, bitShift = 5),
        ParamDef(name = "SpeedMeterConfig1", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01),
        ParamDef(name = "SpeedMeterConfig2", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "FastRE", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "SpecialWeak", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "ZeroSwitch", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "MOE", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "SpeedMeterConfig3", addr = 0x7C, section = "Display", isHiByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "DistanceMSB", addr = 0x7F, section = "Display", scale = 10.0f, unit = "V"),
        ParamDef(name = "ThrottleVoltage", addr = 0x82, section = "Protect", scale = 100.0f, unit = "V"),
        ParamDef(name = "HighVolRestore", addr = 0x83, section = "Protect", scale = 10.0f, unit = "V"),
        ParamDef(name = "MotorTempProtect", addr = 0x84, section = "Protect", isLoByte = true, isSafetyCritical = true),
        ParamDef(name = "MotorTempRestore", addr = 0x84, section = "Protect", isHiByte = true),
        ParamDef(name = "MosTempProtect", addr = 0x85, section = "Protect", isLoByte = true, isSafetyCritical = true),
        ParamDef(name = "MosTempRestore", addr = 0x85, section = "Protect", isHiByte = true),
        ParamDef(name = "CANConfig", addr = 0x86, section = "Display", isLoByte = true, bitMask = 0x3F),
        ParamDef(name = "HardwareVersion", addr = 0x86, section = "Product", isHiByte = true),
        ParamDef(name = "SoftwareVersionMajor", addr = 0x87, section = "Product", isLoByte = true),
        ParamDef(name = "SoftwareVersionMinor", addr = 0x87, section = "Product", isHiByte = true),
        ParamDef(name = "RatioMin", addr = 0x88, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio500", addr = 0x88, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio1000", addr = 0x89, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio1500", addr = 0x89, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio2000", addr = 0x8A, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio2500", addr = 0x8A, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio3000", addr = 0x8B, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio3500", addr = 0x8B, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio4000", addr = 0x8C, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio4500", addr = 0x8C, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio5000", addr = 0x8D, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio5500", addr = 0x8D, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio6000", addr = 0x8E, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio6500", addr = 0x8E, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio7000", addr = 0x8F, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio7500", addr = 0x8F, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio8000", addr = 0x90, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "Ratio8500", addr = 0x90, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "Ratio9000", addr = 0x91, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "RatioMax", addr = 0x91, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "nratio_0", addr = 0x92, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "nratio_1", addr = 0x92, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "nratio_2", addr = 0x93, section = "Energy Regenerate", isLoByte = true),
        ParamDef(name = "nratio_3", addr = 0x93, section = "Energy Regenerate", isHiByte = true),
        ParamDef(name = "nratio_4", addr = 0x94, section = "Ratios in Gear", isLoByte = true),
        ParamDef(name = "nratio_5", addr = 0x94, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_6", addr = 0x95, section = "Ratios in Gear", isLoByte = true),
        ParamDef(name = "nratio_7", addr = 0x95, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_8", addr = 0x96, section = "Ratios in Gear", isLoByte = true),
        ParamDef(name = "nratio_9", addr = 0x96, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_10", addr = 0x97, section = "Ratios in Gear", isLoByte = true),
        ParamDef(name = "nratio_11", addr = 0x97, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_12", addr = 0x98, section = "Ratios in Gear", isLoByte = true),
        ParamDef(name = "nratio_13", addr = 0x98, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_14", addr = 0x99, section = "Ratios in Gear", isLoByte = true),
        ParamDef(name = "nratio_15", addr = 0x99, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_16", addr = 0x9A, section = "Ratios in Gear", scale = 9.0f, isLoByte = true),
        ParamDef(name = "nratio_17", addr = 0x9A, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "nratio_18", addr = 0x9B, section = "Ratios in Gear", scale = 9.0f, isLoByte = true),
        ParamDef(name = "nratio_19", addr = 0x9B, section = "Ratios in Gear", isHiByte = true),
        ParamDef(name = "AN", addr = 0x9C, section = "Ratios in Gear", isLoByte = true, bitMask = 0x0F),
        ParamDef(name = "AlarmRecord_1", addr = 0x9C, section = "Ratios in Gear", isLoByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "RelayOut", addr = 0x9C, section = "Ratios in Gear", isLoByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "EmptySpeed", addr = 0x9C, section = "Ratios in Gear", isLoByte = true, bitMask = 0x03, bitShift = 6),
        ParamDef(name = "LM", addr = 0x9C, section = "Ratios in Gear", isHiByte = true, bitMask = 0x1F),
        ParamDef(name = "InitVol", addr = 0x9D, section = "Ratios in Gear", scale = 9.0f),
        ParamDef(name = "Stage1Curr", addr = 0x9E, section = "Ratios in Gear"),
        ParamDef(name = "VolSelectRatio", addr = 0x9F, section = "Ratios in Gear", scale = 9.0f, isLoByte = true),
        ParamDef(name = "SysCmd", addr = 0xA0, section = "Product", isHiByte = true, isReadOnly = true),
        ParamDef(name = "OneCommSec_0", addr = 0xB4, section = "Functions", isLoByte = true),
        ParamDef(name = "OneCommSec_1", addr = 0xB4, section = "Functions", isHiByte = true),
        ParamDef(name = "OneCommSec_2", addr = 0xB5, section = "Functions", isLoByte = true),
        ParamDef(name = "OneCommSec_3", addr = 0xB5, section = "Functions", isHiByte = true),
        ParamDef(name = "OneCommSec_4", addr = 0xB6, section = "Functions", isLoByte = true),
        ParamDef(name = "OneCommSec_5", addr = 0xB6, section = "Functions", isHiByte = true),
        ParamDef(name = "OneCommSec_6", addr = 0xB7, section = "Functions", isLoByte = true),
        ParamDef(name = "OneCommSec_7", addr = 0xB7, section = "Functions", isHiByte = true),
        ParamDef(name = "PausePosition", addr = 0xB8, section = "Functions", isLoByte = true, bitMask = 0x0F),
        ParamDef(name = "SideStandPosition", addr = 0xB8, section = "Functions", isLoByte = true, bitMask = 0x0F, bitShift = 4),
        ParamDef(name = "HBarPosition", addr = 0xB8, section = "Functions", isHiByte = true, bitMask = 0x0F),
        ParamDef(name = "AntiTheftPosition", addr = 0xB8, section = "Functions", isHiByte = true, bitMask = 0x0F, bitShift = 4),
        ParamDef(name = "Pulse", addr = 0xBA, section = "Functions", isLoByte = true),
        ParamDef(name = "SQH", addr = 0xBA, section = "Functions", isHiByte = true),
        ParamDef(name = "OnelineCurrCoeff", addr = 0xBB, section = "Functions"),
        ParamDef(name = "BackPTime", addr = 0xBC, section = "Energy Regenerate", isLoByte = true, bitMask = 0x1F),
        ParamDef(name = "ReleaseToSeat", addr = 0xBC, section = "Functions", isLoByte = true, bitMask = 0x07, bitShift = 5),
        ParamDef(name = "Stage1Soc", addr = 0xBD, section = "Functions", isLoByte = true),
        ParamDef(name = "Stage2Soc", addr = 0xBD, section = "Functions", isHiByte = true),
        ParamDef(name = "AccCoeff", addr = 0xBE, section = "Functions", isHiByte = true, bitMask = 0x0F, bitShift = 4),
        ParamDef(name = "BstTime", addr = 0xBF, section = "Functions", scale = 500.0f),
        ParamDef(name = "BstRelease", addr = 0xC0, section = "Functions", scale = 500.0f),
        ParamDef(name = "ParkTime", addr = 0xC1, section = "Functions", scale = 500.0f),
        ParamDef(name = "ReverseTime", addr = 0xC2, section = "Functions", isLoByte = true, bitMask = 0x3F),
        ParamDef(name = "JLNationalStandardStatus", addr = 0xC2, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "Press2ForP", addr = 0xC2, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "LowMediumToHighSpeed", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01),
        ParamDef(name = "NoSoundPrompt", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "SilenceBuzzer", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "EnableBackupBuzzer", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "DisableMotorAngleSensorRepair", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "AllowBrakeFaultRepair", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "ReverseOneLine", addr = 0xC2, section = "Functions", isHiByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "TorqueCoeff", addr = 0xC3, section = "Functions"),
        ParamDef(name = "IdleClutchFunction", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01),
        ParamDef(name = "AutomaticVoltageSwitching", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "ReverseNeutralForIgnition", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "KnobToAdjustMaximumBusBar", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "OneTouchRepairSwitching", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "SqueezeBrake2xForPark", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "SqueezeBrakeToReleasePark", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "SingleCellNoBoost", addr = 0xC4, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "LearnVolLow", addr = 0xC4, section = "Functions", isHiByte = true),
        ParamDef(name = "TapForwardAndBack", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01),
        ParamDef(name = "DualThrottleVoltage", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 1),
        ParamDef(name = "CenterThrottleNeutral", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "EnableOneClickRepair", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "EnhancedInpuSignalFiltering", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 4),
        ParamDef(name = "UnlimitedCruiseSpeed", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 5),
        ParamDef(name = "HallDetectionX6", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 6),
        ParamDef(name = "NewMTPAVector", addr = 0xC5, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 7),
        ParamDef(name = "LearnVolHigh", addr = 0xC5, section = "Functions", isHiByte = true),
        ParamDef(name = "SlowDownRpm", addr = 0xC6, section = "Functions"),
        ParamDef(name = "StartIs", addr = 0xC7, section = "Functions"),
        ParamDef(name = "ThrottleInsert", addr = 0xC8, section = "Functions"),
        ParamDef(name = "ExitFollowSpeed", addr = 0xC9, section = "Functions", isLoByte = true),
        ParamDef(name = "ReCurrRatio", addr = 0xC9, section = "Functions", isHiByte = true),
        ParamDef(name = "AngleLearn", addr = 0xCA, section = "Functions", isLoByte = true),
        ParamDef(name = "NoCanCnt", addr = 0xCA, section = "Functions", isHiByte = true),
        ParamDef(name = "Temp70", addr = 0xCB, section = "Functions", isLoByte = true, bitMask = 0x03),
        ParamDef(name = "LongBack", addr = 0xCB, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 2),
        ParamDef(name = "ThrottleLost", addr = 0xCB, section = "Functions", isLoByte = true, bitMask = 0x01, bitShift = 3),
        ParamDef(name = "LearnThrottle", addr = 0xCB, section = "Functions", isHiByte = true),
        ParamDef(name = "SpeedLowCap", addr = 0xCC, section = "Functions", isLoByte = true),
        ParamDef(name = "MidSpeedCap", addr = 0xCC, section = "Functions", isHiByte = true),
        ParamDef(name = "SpeedLimitByCap", addr = 0xCD, section = "Functions", isLoByte = true),
        ParamDef(name = "MinSpeedCapCoeff", addr = 0xCD, section = "Functions", isHiByte = true),
        ParamDef(name = "ParkCoeff", addr = 0xCE, section = "Functions", isLoByte = true, bitMask = 0x0F),
        ParamDef(name = "ReIsinAcc", addr = 0xCE, section = "Functions"),
        ParamDef(name = "Data0", addr = 0xD0, section = "Display", isLoByte = true),
        ParamDef(name = "Data1", addr = 0xD0, section = "Display", isHiByte = true),
        ParamDef(name = "BMQHALL", addr = 0xD1, section = "Display", isLoByte = true),
        ParamDef(name = "AVGPower", addr = 0xD1, section = "Display", isHiByte = true),
        ParamDef(name = "WheelRatio", addr = 0xD2, section = "Display", isLoByte = true),
        ParamDef(name = "WheelRadius", addr = 0xD2, section = "Display", isHiByte = true),
        ParamDef(name = "AVGSpeed", addr = 0xD3, section = "Display", isLoByte = true),
        ParamDef(name = "WheelWidth", addr = 0xD3, section = "Display", isHiByte = true),
        ParamDef(name = "RateRatio", addr = 0xD4, section = "Display"),
        ParamDef(name = "ByteOption", addr = 0xD5, section = "Display", isLoByte = true, bitMask = 0x0F),
        ParamDef(name = "Global_state1a", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "RunDir1", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "HallPosError", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "Global_state1b", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "AutoLearn", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "NeedAutoLearn", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "Global_state1c", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "HallError", addr = 0xD7, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "MotorRun", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "Global_state1d", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "Global_state1e", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "PhaseLostAlarm", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "MotorCloseEnable", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "MotorRun2", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "VoltageReport", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "AngleFix", addr = 0xD7, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "FlashWay", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "Global_state_2a", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "INVControl", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "WeakStat", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "LowVolStop", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "LowVolControl", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "EABSStart", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "Exchange", addr = 0xD8, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "Global_state_2b", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "GearDisable", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "DefaultFW", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "SpeedLimit", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "MidSpeedEnabled", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "HighSpeedEnabled", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "FDEnable", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "FDBrake", addr = 0xD8, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "Global_state3", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "FDStart", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "FDClose", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "FDWay", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "SpeedLimitEnabled", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "PhaseCZero", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "FDWork", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "WUVD", addr = 0xD9, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "PhaseAZero", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "ShouldBeStat", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "ZeroUseable", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "VUWD", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "WUUD", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "UUWD", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "VUUD", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "UUVD", addr = 0xD9, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "VolFlash", addr = 0xDA, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "FlashError", addr = 0xDA, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "DeadZone", addr = 0xDA, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "CANType", addr = 0xDA, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "Zsignal", addr = 0xDA, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "ABError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "ZError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "PError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "MagnetError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "ZABError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "PABError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "AngleError", addr = 0xDA, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "MosTemp", addr = 0xDB, section = "Diagnostics", isReadOnly = true),
        ParamDef(name = "forward", addr = 0xE2, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "reverse", addr = 0xE2, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "gear", addr = 0xE2, section = "Diagnostics", isLoByte = true, bitMask = 0x03, bitShift = 2, isReadOnly = true),
        ParamDef(name = "sliding_backwards", addr = 0xE2, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "motion", addr = 0xE2, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "compPhoneOK", addr = 0xE2, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "phaseA_active", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "phaseB_active", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "phaseC_active", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "passOK", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x03, bitShift = 3, isReadOnly = true),
        ParamDef(name = "Bmq_Hall", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "LowVolRem", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "MosfetCheck", addr = 0xE2, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "motor_hall_error", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "throttle_error", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "current_protect_restart", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "phase_current_surge_protect", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "voltage_protect", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "alarm_protect", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "motor_temp_protect", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "controller_temp_protect", addr = 0xE3, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "phase_current_overflow_protect", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "phase_zero_error", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "phase_int16_t_protect", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 2, isReadOnly = true),
        ParamDef(name = "line_current_zero_error", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 3, isReadOnly = true),
        ParamDef(name = "mosfet_high_side_error", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "mosfet_low_side_error", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "moe_current_protect", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "brake", addr = 0xE3, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "modulation", addr = 0xE4, section = "Diagnostics", scale = 128.0f, isLoByte = true, isReadOnly = true),
        ParamDef(name = "MeasureSpeed", addr = 0xE5, section = "Diagnostics", isReadOnly = true),
        ParamDef(name = "deci_volts", addr = 0xE8, section = "Diagnostics", scale = 10.0f, unit = "V", isReadOnly = true),
        ParamDef(name = "per_mille", addr = 0xE9, section = "Diagnostics", scale = 4096.0f, isReadOnly = true),
        ParamDef(name = "lineCurrent", addr = 0xEA, section = "Diagnostics", scale = 4.0f, unit = "A", isReadOnly = true),
        ParamDef(name = "ThrottleDepth", addr = 0xED, section = "Diagnostics", isReadOnly = true),
        ParamDef(name = "volts", addr = 0xF1, section = "Diagnostics", scale = 16.0f, isReadOnly = true),
        ParamDef(name = "motor_temp", addr = 0xF4, section = "Diagnostics", isReadOnly = true),
        ParamDef(name = "batt_cap", addr = 0xF5, section = "Diagnostics", isHiByte = true, isReadOnly = true),
        ParamDef(name = "ModifyYear", addr = 0xF6, section = "Diagnostics", isHiByte = true, isReadOnly = true),
        ParamDef(name = "ModifyMonth", addr = 0xF7, section = "Diagnostics", isLoByte = true, isReadOnly = true),
        ParamDef(name = "ModifyDay", addr = 0xF7, section = "Diagnostics", isHiByte = true, isReadOnly = true),
        ParamDef(name = "EXETotal", addr = 0xF8, section = "Diagnostics", scale = 8.0f, isReadOnly = true),
        ParamDef(name = "EXESingle", addr = 0xF9, section = "Diagnostics", scale = 8.0f, isReadOnly = true),
        ParamDef(name = "PhaseAZero2", addr = 0xFA, section = "Diagnostics", isReadOnly = true),
        ParamDef(name = "PhaseCZero2", addr = 0xFB, section = "Diagnostics", isReadOnly = true),
        ParamDef(name = "ErrorStop", addr = 0xFC, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "old_blue", addr = 0xFC, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "BlockStat", addr = 0xFC, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "EABSStat", addr = 0xFC, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "BrakeControl", addr = 0xFC, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
        ParamDef(name = "motor_running_state_0", addr = 0xFE, section = "Diagnostics", isLoByte = true, bitMask = 0x01, isReadOnly = true),
        ParamDef(name = "motor_running_state_1", addr = 0xFE, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 1, isReadOnly = true),
        ParamDef(name = "motor_running_state_2", addr = 0xFE, section = "Diagnostics", isLoByte = true, bitMask = 0x03, bitShift = 2, isReadOnly = true),
        ParamDef(name = "motor_running_state_4", addr = 0xFE, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "motor_running_state_5", addr = 0xFE, section = "Diagnostics", isLoByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "motor_running_state_6", addr = 0xFE, section = "Diagnostics", isLoByte = true, bitMask = 0x03, bitShift = 6, isReadOnly = true),
        ParamDef(name = "GearControl", addr = 0xFE, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 4, isReadOnly = true),
        ParamDef(name = "HXControl", addr = 0xFE, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 5, isReadOnly = true),
        ParamDef(name = "TbarControl", addr = 0xFE, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 6, isReadOnly = true),
        ParamDef(name = "HbarControl", addr = 0xFE, section = "Diagnostics", isHiByte = true, bitMask = 0x01, bitShift = 7, isReadOnly = true),
    )
}
