package com.bretthalliday.fdtuner.model

/**
 * GENERATED from the FarDriver factory-app settings documentation.
 * Per-parameter help text, safe recommendations, defaults, examples, warnings, and (where the
 * docs give a clean numeric range) write bounds. Keyed by the OFFICIAL menu name — matches the
 * curated ParamDefinitions names. Merge into ParamDef.notes / minVal / maxVal and show `warning`
 * prominently in the edit dialog.
 */
data class ParamDoc(
    val help: String = "",
    val recommendation: String = "",
    val default: String = "",
    val examples: String = "",
    val warning: String = "",
    val minVal: Int? = null,
    val maxVal: Int? = null,
)

data class PidPreset(
    val name: String,
    val startKI: Int, val midKI: Int, val maxKI: Int,
    val startKP: Int, val midKP: Int, val maxKP: Int,
)

object ParamDocs {
    val byName: Map<String, ParamDoc> = mapOf(
        "Speed Pulses" to ParamDoc(help = ""),
        "Adjust Speed Pulses" to ParamDoc(help = ""),
        "SpeedoMeter" to ParamDoc(help = ""),
        "CAN" to ParamDoc(help = ""),
        "CAN Baud" to ParamDoc(help = ""),
        "Step" to ParamDoc(help = ""),
        "SpecialFrame" to ParamDoc(help = ""),
        "SQH" to ParamDoc(help = ""),
        "DATA1" to ParamDoc(help = ""),
        "SEC1" to ParamDoc(help = ""),
        "SEC3" to ParamDoc(help = ""),
        "SEC5" to ParamDoc(help = ""),
        "SEC7" to ParamDoc(help = ""),
        "BCPosition" to ParamDoc(help = ""),
        "FDPosition" to ParamDoc(help = ""),
        "ByteOption" to ParamDoc(help = ""),
        "WheelRatio" to ParamDoc(help = ""),
        "Check WheelRatio" to ParamDoc(help = ""),
        "GearRatio" to ParamDoc(help = ""),
        "Check GearRatio" to ParamDoc(help = ""),
        "SpdPulseNum" to ParamDoc(help = ""),
        "AnalogSpeedCoeff" to ParamDoc(help = ""),
        "CAN Detect" to ParamDoc(help = ""),
        "TorqueCoeff" to ParamDoc(help = ""),
        "Stop" to ParamDoc(help = ""),
        "PULSE" to ParamDoc(help = ""),
        "DATA0" to ParamDoc(help = ""),
        "SEC0" to ParamDoc(help = ""),
        "SEC2" to ParamDoc(help = ""),
        "SEC4" to ParamDoc(help = ""),
        "SEC6" to ParamDoc(help = ""),
        "PPosition" to ParamDoc(help = ""),
        "HbarPosition" to ParamDoc(help = ""),
        "CurrentCoeff" to ParamDoc(help = ""),
        "WheelWidth" to ParamDoc(help = ""),
        "WheelR" to ParamDoc(help = ""),
        "StopBackCurr" to ParamDoc(help = "Controls regen current allowed at very low RPM / near standstill."),
        "Batt RatedCapacity" to ParamDoc(help = "Battery capacity in Ah.", recommendation = "Enter actual battery capacity", examples = "40Ah battery → 40; 60Ah battery → 60; 100Ah battery → 100; Used by:; Battery calculations; Capacity estimation functions"),
        "FreeThrottle" to ParamDoc(help = "Controls throttle free-play before regen activates."),
        "Increase FreeThrottle" to ParamDoc(help = ""),
        "Regen Curve Point #1" to ParamDoc(help = ""),
        "Regen Curve Point #2" to ParamDoc(help = ""),
        "Regen Curve Point #3" to ParamDoc(help = ""),
        "Regen Curve Point #4" to ParamDoc(help = ""),
        "Regen Curve Point #5" to ParamDoc(help = ""),
        "Regen Curve Point #6" to ParamDoc(help = ""),
        "Regen Curve Point #7" to ParamDoc(help = ""),
        "Regen Curve Point #8" to ParamDoc(help = ""),
        "Regen Curve Point #9" to ParamDoc(help = ""),
        "MaxBackCurr" to ParamDoc(help = "Maximum regenerative braking current. This is the primary regen strength limiter."),
        "Reduce MaxBackCurr" to ParamDoc(help = ""),
        "Regen Curve Point #10" to ParamDoc(help = ""),
        "Regen Curve Point #11" to ParamDoc(help = ""),
        "Regen Curve Point #12" to ParamDoc(help = ""),
        "Regen Curve Point #13" to ParamDoc(help = ""),
        "Regen Curve Point #14" to ParamDoc(help = ""),
        "Regen Curve Point #15" to ParamDoc(help = ""),
        "Regen Curve Point #16" to ParamDoc(help = ""),
        "Regen Curve Point #17" to ParamDoc(help = ""),
        "Regen Curve Point #18" to ParamDoc(help = ""),
        "Boost Pin" to ParamDoc(help = ""),
        "SideStand Pin" to ParamDoc(help = ""),
        "Forward Pin" to ParamDoc(help = ""),
        "Highspeed Pin" to ParamDoc(help = ""),
        "Charge Pin" to ParamDoc(help = ""),
        "Seat Pin" to ParamDoc(help = ""),
        "Switch Voltage Pin" to ParamDoc(help = ""),
        "BoostTime" to ParamDoc(help = ""),
        "HighLowSpeed" to ParamDoc(help = ""),
        "EmptyRun" to ParamDoc(help = ""),
        "Gear" to ParamDoc(help = ""),
        "Brake" to ParamDoc(help = ""),
        "Park" to ParamDoc(help = ""),
        "Cruise Pin" to ParamDoc(help = ""),
        "Pause Pin" to ParamDoc(help = ""),
        "Backward Pin" to ParamDoc(help = ""),
        "LowSpeed Pin" to ParamDoc(help = ""),
        "Anti-theft Pin" to ParamDoc(help = ""),
        "SpeedLimit Pin" to ParamDoc(help = ""),
        "Repair Pin" to ParamDoc(help = ""),
        "BoostRelease" to ParamDoc(help = ""),
        "Puse RE" to ParamDoc(help = ""),
        "SlowDown" to ParamDoc(help = ""),
        "PC13" to ParamDoc(help = ""),
        "Follow" to ParamDoc(help = ""),
        "AngleDetect" to ParamDoc(help = "Stores hall angle information found during auto learn. Normally set automatically by auto learn Do not manually change unless diagnosing motor issues", recommendation = "Leave on auto-detected value"),
        "PhaseOffset" to ParamDoc(help = "Electrical phase timing offset between halls and motor phases. Set automatically during auto learn Wrong value can cause rough running, heat, or poor efficiency", recommendation = "Leave auto-learned value"),
        "Motor Direction" to ParamDoc(help = "Changes motor rotation direction."),
        "RatedVoltage" to ParamDoc(help = "Nominal battery voltage.", examples = "48V system → 48; 60V system → 60; 72V system → 72; 84V system → 84; 96V system → 96; Must match battery system voltage."),
        "MaxSpeed" to ParamDoc(help = "Maximum motor RPM limit. Acts as RPM limiter Too low = reduced top speed Too high = no limiting", recommendation = "Set above expected operating RPM Usually determined from motor specifications"),
        "MaxLineCurr" to ParamDoc(help = "Maximum battery current (bus current).", examples = "100A battery → 100A limit; 200A battery → 200A limit", warning = "Never exceed battery BMS capability Never exceed controller capability"),
        "ThrottleResponse" to ParamDoc(help = "Overall throttle sensitivity. Higher = sharper response Lower = smoother response"),
        "BoostLineCurr" to ParamDoc(help = "Temporary battery current limit during boost. Used with boost feature Only active when boost input/function is triggered"),
        "PhaseExchange" to ParamDoc(help = "Software phase swap.", recommendation = "Leave disabled unless specifically needed"),
        "Weak Character" to ParamDoc(help = "Field weakening characteristic profile.", recommendation = "Usually left at learned/default value"),
        "Throttle Dec Step" to ParamDoc(help = "Throttle release ramp speed.", default = "224", minVal = 180, maxVal = 250),
        "Throttle Low" to ParamDoc(help = "Minimum recognized throttle voltage.", default = "Approximately 0.9V Correct setup: Open Graph tab Read resting throttle voltage S", examples = "Resting throttle = 0.82V; Set Throttle Low = 0.92V", warning = "Dead throttle zone Ghost throttle Startup throttle faults"),
        "TempSensor" to ParamDoc(help = "Selects motor temperature sensor type."),
        "PolePairs" to ParamDoc(help = "Number of motor pole pairs.", examples = "QS138 = 5; QS205 V3 = 16; QS273 V2 = 28; Must match motor specification."),
        "RatedSpeed" to ParamDoc(help = "Motor rated RPM.", examples = "QS138 70H = 3800 RPM; QS138 90H = 4000 RPM; Must be mechanical RPM."),
        "RatedPower" to ParamDoc(help = "Motor rated wattage.", examples = "3000W; 5000W; 8000W; Should match motor specifications."),
        "BackSpeed" to ParamDoc(help = "Maximum reverse RPM.", recommendation = "Keep relatively low for safety"),
        "MaxPhaseCurr" to ParamDoc(help = "Maximum motor phase current."),
        "Throttle Acc Step" to ParamDoc(help = "Throttle application ramp speed.", default = "220 Common tuning: 180-200 smoother 220 default 240+ aggressive"),
        "BoostPhaseCurr" to ParamDoc(help = "Temporary phase current limit during boost. Only active while boost is engaged."),
        "ECOAccCoeff" to ParamDoc(help = "Eco mode acceleration reduction. Higher reduction = softer acceleration Lower reduction = stronger acceleration"),
        "WeakResponse" to ParamDoc(help = ""),
        "Release Throttle" to ParamDoc(help = "Controls behavior when throttle is released."),
        "Throttle High" to ParamDoc(help = "Maximum recognized throttle voltage. First field weakening curve point. RPM = activation point Percentage = field weakening strength at that RPM D-axis inductance value. Learned automatically during Auto Learn. Used internally by the contro", default = "Approximately 4.0V Correct setup: Read full throttle voltage in Graph tab Set Th", examples = "Full throttle = 4.18V; Set Throttle High = 4.08V; RATIOS IN SPEED MENU; What this menu does; This menu controls:; Field Weakening activation; Field Weakening strength curve; High-speed performance; Top speed behavior; Motor inductance value"),
        "ReCurrRatio" to ParamDoc(help = ""),
        "VolSelectRatio" to ParamDoc(help = ""),
        "Re Acc" to ParamDoc(help = ""),
        "RelayDelay" to ParamDoc(help = ""),
        "BCEnable" to ParamDoc(help = ""),
        "PEnable" to ParamDoc(help = ""),
        "CruiseEnable" to ParamDoc(help = ""),
        "PushEnable" to ParamDoc(help = ""),
        "OverSpeedAlarm" to ParamDoc(help = ""),
        "RememberGear" to ParamDoc(help = ""),
        "RelayDelay1S" to ParamDoc(help = ""),
        "StartIs" to ParamDoc(help = ""),
        "Curr-Anti-theft" to ParamDoc(help = ""),
        "Temp 70" to ParamDoc(help = ""),
        "InverseTime" to ParamDoc(help = ""),
        "SlowDownCoeff" to ParamDoc(help = ""),
        "LearnThrottle" to ParamDoc(help = ""),
        "LearnVolHigh" to ParamDoc(help = ""),
        "DeepWeak" to ParamDoc(help = ""),
        "FwReRatio" to ParamDoc(help = ""),
        "WeakCurrCoeff" to ParamDoc(help = ""),
        "AlarmDelay" to ParamDoc(help = ""),
        "RelayOut" to ParamDoc(help = ""),
        "SeatEnable" to ParamDoc(help = ""),
        "AutoBackPEnable" to ParamDoc(help = ""),
        "EABSEnable" to ParamDoc(help = ""),
        "BackEnable" to ParamDoc(help = ""),
        "HigiVolProtect" to ParamDoc(help = ""),
        "LowVolProtect" to ParamDoc(help = ""),
        "MotorTempProtect" to ParamDoc(help = ""),
        "MosTempProtect" to ParamDoc(help = ""),
        "0 BattCoeff" to ParamDoc(help = ""),
        "ThrottleLost" to ParamDoc(help = "Throttle-loss protection. Monitors: Missing throttle signal Invalid throttle input Can trigger safety behavior if throttle signal disappears."),
        "BackP_Time" to ParamDoc(help = ""),
        "BlockTime" to ParamDoc(help = "Motor block/stall protection timing. If motor becomes stalled: Controller monitors duration Protection can activate Helps protect: Motor Controller Wiring"),
        "LmtSpdStartCap" to ParamDoc(help = ""),
        "LmtSpdMaxCoeff" to ParamDoc(help = ""),
        "BattSignal" to ParamDoc(help = ""),
        "IntRes" to ParamDoc(help = "Battery internal resistance value."),
        "HigiVolRestore" to ParamDoc(help = "Voltage level where controller resumes operation after high-voltage fault clears. Usually set slightly below: HigiVolProtect"),
        "LowVolRestore" to ParamDoc(help = "Voltage level where controller resumes operation after low-voltage condition clears. Usually set slightly above: LowVolProtect"),
        "MotorTempRestore" to ParamDoc(help = "Motor temperature at which protection is removed.", examples = "Protect at 120°C; Restore at 100°C; Prevents constant cycling."),
        "MosTempRestore" to ParamDoc(help = "Controller temperature recovery point. Controller resumes normal operation after cooling below this value."),
        "Full BattCoeff" to ParamDoc(help = "Motor control coefficient. Verified guidance from documentation: For hub motors: AN = 0-4 If AN is too high: MOE faults OVER faults PHASE faults may occur. StartKI (PID Paras → Left column → #2) Integral gain during startup. Lower values: M", recommendation = "Leave unchanged unless specifically tuning speed control. MOE (PID Paras → Left column → #6)", default = "LM = 22 Known tuning guidance: If motor is rough or jerky: 22 → 16 → 14 → 12 → 1"),
        "ThrottleInsert" to ParamDoc(help = ""),
        "ReleaseToSeat" to ParamDoc(help = ""),
        "ParkTime" to ParamDoc(help = ""),
        "LmtSpdMinCap" to ParamDoc(help = ""),
        "TurtleSpeedCurrCoeff" to ParamDoc(help = ""),
        "LowVol Way" to ParamDoc(help = ""),
        "电池内阻" to ParamDoc(help = ""),
        "LowSpeedLineRatio" to ParamDoc(help = ""),
        "LowSpeedPhaseRatio" to ParamDoc(help = ""),
        "LowSpeed" to ParamDoc(help = ""),
        "MidSpeedLineRatio" to ParamDoc(help = ""),
        "MidSpeedPhaseRatio" to ParamDoc(help = ""),
        "MiddleSpeed" to ParamDoc(help = ""),
    )

    /** Factory PID tune ladder (writes all six KI/KP values when applied). */
    val pidPresets: List<PidPreset> = listOf(
        PidPreset("Very soft", 16, 16, 24, 160, 160, 240),
        PidPreset("Soft", 8, 16, 24, 80, 160, 240),
        PidPreset("Medium-soft", 8, 8, 12, 80, 80, 120),
        PidPreset("Medium Power Default", 4, 8, 12, 40, 80, 120),
        PidPreset("Aggressive", 4, 4, 6, 40, 40, 60),
        PidPreset("High Power Default", 2, 4, 6, 20, 40, 60),
        PidPreset("Very aggressive", 2, 2, 3, 20, 20, 30),
        PidPreset("Race style", 1, 2, 3, 10, 20, 30),
        PidPreset("Surfboard Default", 1, 1, 1, 10, 10, 10),
    )
}